version: '3.8'

services:
  api-flow-stock:
   build: .
   container_name: api-flow-stock
   #comportamento caso seja reinicado o container
   restart: unless-stopped
   ports:
     - "3000:3000" #porta do host:porta do container
   environment:
      - NODE_ENV=production #variavel de ambiente para o node
      - PORT=3000 #porta do node
      - MYSQL_TYPE=mysql #host do mysql
      - MYSQL_HOST=api-flowstock.cgle8akogsgx.us-east-1.rds.amazonaws.com
      - MYSQL_PORT=3306 #porta do mysql
      - MYSQL_SYNCHRONIZE=true
      - MYSQL_DATABASE=flowstock
      - MYSQL_USERNAME=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=4144$1503aA
  depends_on:
    - mysql #nome do serviço mysql
  networks:
    - api-flow-stock-network #rede do container
  mysql:  
    image: mysql:5.7 #imagem do mysql
    container_name: mysql-flow-stock #nome do container mysql
    restart: unless-stopped #comportamento caso seja reinicado o container
    environment:
      - MYSQL_DATABASE=flowstock #nome do banco de dados
      - MYSQL_HOST=api-flowstock.cgle8akogsgx.us-east-1.rds.amazonaws.com #host do mysql
      - MYSQL_PORT=3306 #porta do mysql
      - MYSQL_TYPE=mysql #tipo do mysql
      - MYSQL_USER=admin #usuario do mysql
      - MYSQL_PASSWORD=4144$1503aA #senha do mysql
    volumes:
      - mysql-data:/var/lib/mysql #volume do mysql
    networks:
      - api-flow-stock-network #rede do container
    ports:
      - "3306:3306" #porta do host:porta do container
    
volumes:
  mysql-data: #volume do mysql
    driver: local #driver do volume
      
